name: cache dependencies
description: this action is for caching dependencies

runs:
  using: "composite"
  steps:
    - name: cache depend
      run: |
        echo "checking for hardcoded AWS keys in the git diff"
        if git diff --cached | grep -E 'AKIA[0-9A-Z]{16}' then
          echo "Found possible AWS key"
          exit 1
        else
          echo "no secrets found"
      shell: bash
    
    - name: print github action context values
      run: | 
        echo "Event: ${{ toJson(github.event)  }}"
        echo "Action path: ${{ github.action_path }}"
      shell: bash