name: cache dependencies
description: this action is for caching dependencies

runs:
  using: "composite"
  steps:
    - name: cache depend
      run: |
        echo "checking for hardcoded AWS keys in the git diff"
        if git diff --cached | grep -E 'AKIA[0-9A-Z]{16}'; then
          echo "Found possible AWS key"
          exit 1
        else
          echo "no secrets found"
        fi
      shell: bash
    
    - name: print github action context values
      run: | 
        echo "Event: ${{ toJson(github.event)  }}"
        echo "Action path: ${{ github.action_path }}"
        echo "Github env: $GITHUB_ENV"
        echo "APP_ENV=dev" >> $GITHUB_ENV
      shell: bash

    - name: test executing script from script file
      run: |
        chmod +x ${{ github.action_path }}/scripts/printenv.sh
        ${{ github.action_path }}/scripts/printenv.sh
      shell: bash