name: "Deploy to ECS"
inputs:
  cluster_name:
    required: true
  service_name:
    required: true
  image_tag:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        TASK_DEFINITION=$(aws ecs describe-services \
          --cluster ${{ inputs.cluster_name }} \
          --services ${{ inputs.service_name }} \
          --query "services[0].taskDefinition" \
          --output text)

        IMAGE_URI=$(aws ecs describe-task-definition \
          --task-definition $TASK_DEFINITION \
          --query "taskDefinition.containerDefinitions[0].image" \
          --output text | sed "s/:.*/:${{ inputs.image_tag }}/")

        NEW_TASK_DEF=$(aws ecs register-task-definition \
          --cli-input-json "$(aws ecs describe-task-definition \
            --task-definition $TASK_DEFINITION \
            --query 'taskDefinition' | \
            jq --arg IMAGE "$IMAGE_URI" \
              '.containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy, .tags)')")

        aws ecs update-service \
          --cluster ${{ inputs.cluster_name }} \
          --service ${{ inputs.service_name }} \
          --force-new-deployment
