name: testing the custom actions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose environment
        required: true
        type: choice
        options: [dev, stage, prod]
        default: dev

jobs:
  testing-action:
    name: testing action
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repo
        uses: actions/checkout@v4

      - name: checking aws keys in cache
        uses: ./.github/actions/cache-depend

      - name: environment action checker
        id: env_check
        uses: ./.github/actions/environment-checker
        with:
          environment: ${{ github.event.inputs.environment }}
      
      - name: conditional step
        if: steps.env_check.outputs.is_dev == 'true'
        run: echo "running dev only step"

      

